cleanup and reduce bin size (#10)
* cleanup and reduce bin size

 - avoid leaking chan in runDaemon
 - prevent any file corruption in runDaemon
 - removes go-chi dep in favor of std lib
 - harmonize (a bit) usage of logrus
 - implement graceful shutdown
 - add basic lint with travis
 - allow go tip to fail

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 # a hack to generate releases like other prometheus projects
 # use like this:
-#       VERSION=1.0.1 ./release.sh
-set -e
+#       GITHUB_TOKEN=xxxx VERSION=0.2.2 scripts/release
+set -ex
 
 # github user and repo
 USER=messagebird
@@ -12,6 +12,11 @@ BIN_DIR=bin
 
 if [ -z "$VERSION" ]; then
     >&2 echo "missing VERSION=X.X.X"
+    exit 1
+fi
+
+if [ -z "GITHUB_TOKEN" ]; then
+    >&2 echo "missing GITHUB_TOKEN=xxx"
     exit 1
 fi
 
